POST http://localhost:8080/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password":""
}
###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password":""
}

###
POST http://localhost:8080/scan
Content-Type: application/json

{
    "origin": "64674ca707dbc9206e0098e1",
    "host":"127.0.0.1",
    "scanType":"-sS",
    "maxRetries":"10",
    "hostTimeout":"1000",
    "port":"8080"
}

###
GET http://localhost:8080/history?origin=64674ca707dbc9206e0098e1

###
GET http://localhost:8080/result?origin=64674ca707dbc9206e0098e1